package com.margelo.nitro.spotlight

import android.view.View
import com.facebook.react.bridge.UiThreadUtil
import com.facebook.react.uimanager.UIManagerHelper
import com.facebook.react.uimanager.common.UIManagerType
import com.facebook.react.fabric.FabricUIManager
import com.facebook.react.uimanager.ThemedReactContext
import com.margelo.nitro.views.RecyclableView

// NOTE: HybridSpotlightViewSpec is generated by `npx nitrogen` from Spotlight.nitro.ts.
// It extends HybridObject and provides prop/method stubs to implement.

/**
 * HybridSpotlightView
 *
 * Nitro HybridView for the walkthrough spotlight overlay.
 *
 * Architecture:
 *  - SpotlightDrawingView  handles all drawing (dim + PorterDuff CLEAR cutout + ring).
 *  - This class handles the Nitro bridge: props → drawing view, methods → drawing view.
 *  - measureViewByTag uses FabricUIManager (new arch only, no ReactInstanceManager needed).
 *
 * Threading:
 *  - Props set via React JSX arrive on the UI thread (Fabric guarantee).
 *  - Methods called via hybridRef may arrive on any thread; we marshal to UI thread.
 */
class HybridSpotlightView(private val context: ThemedReactContext) :
    HybridSpotlightViewSpec(), RecyclableView {

    // ── Backing drawing view ──────────────────────────────────────────────────

    private val spotlightView = SpotlightDrawingView(context)

    /** Nitro requires this accessor to hand the view to Fabric. */
    override val view: View
        get() = spotlightView

    // ── Props ─────────────────────────────────────────────────────────────────

    override var dimOpacity: Double = 0.55
        set(v) {
            field = v
            // Props arrive on UI thread from Fabric; direct call is safe.
            spotlightView.dimOpacity = v.toFloat()
        }

    override var cornerRadius: Double = 12.0
        set(v) {
            field = v
            spotlightView.cornerRadius = v.toFloat()
        }

    override var padding: Double = 6.0
        set(v) {
            field = v
            spotlightView.padding = v.toFloat()
        }

    /**
     * Callback fired after each highlight/highlightAnimated call.
     * Wrapped via callback() on the JS side (Nitro view callback requirement).
     */
    override var onTargetLayout: ((TargetRect) -> Unit)? = null

    // ── Methods ───────────────────────────────────────────────────────────────

    /**
     * Instantly position the spotlight at [x, y, width, height] (window-space dp).
     */
    override fun highlight(x: Double, y: Double, width: Double, height: Double) {
        UiThreadUtil.runOnUiThread {
            spotlightView.setHighlight(
                x.toFloat(), y.toFloat(),
                width.toFloat(), height.toFloat(),
                animated = false,
            )
            onTargetLayout?.invoke(TargetRect(x = x, y = y, width = width, height = height))
        }
    }

    /**
     * Animate the spotlight to [x, y, width, height] (window-space dp).
     * Fires onTargetLayout immediately so the JS tooltip can start positioning
     * while the native animation plays behind it.
     */
    override fun highlightAnimated(
        x: Double,
        y: Double,
        width: Double,
        height: Double,
        durationMs: Double,
    ) {
        UiThreadUtil.runOnUiThread {
            spotlightView.setHighlight(
                x.toFloat(), y.toFloat(),
                width.toFloat(), height.toFloat(),
                animated  = true,
                durationMs = durationMs.toLong(),
            )
            // Fire immediately — tooltip positions itself while animation plays.
            onTargetLayout?.invoke(TargetRect(x = x, y = y, width = width, height = height))
        }
    }

    /**
     * Hide and clear the spotlight (animated collapse to center).
     */
    override fun clear() {
        UiThreadUtil.runOnUiThread {
            spotlightView.clear()
        }
    }

    /**
     * Measure any React Native view by its react tag (from findNodeHandle on JS side).
     *
     * Uses FabricUIManager — new arch only, no ReactInstanceManager required.
     * Runs sync on the UI thread via runOnUiThread (blocks calling thread briefly).
     *
     * Returns window-space dp coordinates, matching RN's pageX/pageY convention.
     */
    override fun measureViewByTag(reactTag: Double): TargetRect {
        var result = TargetRect(x = 0.0, y = 0.0, width = 0.0, height = 0.0)

        // FabricUIManager can only be accessed on the UI thread.
        UiThreadUtil.runOnUiThread {
            val fabricUIManager = UIManagerHelper.getUIManager(
                context,
                UIManagerType.FABRIC,
            ) as? FabricUIManager ?: return@runOnUiThread

            // resolveView returns the actual Android View for a given react tag.
            // This is the correct new arch API — no legacy UIManagerModule needed.
            val targetView: View = fabricUIManager.resolveView(reactTag.toInt())
                ?: return@runOnUiThread

            val density  = context.resources.displayMetrics.density
            val location = IntArray(2)

            // getLocationInWindow gives coordinates relative to the window root,
            // matching what JS pageX/pageY returns. Divide by density → dp.
            targetView.getLocationInWindow(location)

            result = TargetRect(
                x      = location[0] / density.toDouble(),
                y      = location[1] / density.toDouble(),
                width  = targetView.width  / density.toDouble(),
                height = targetView.height / density.toDouble(),
            )
        }

        return result
    }

    // ── RecyclableView ────────────────────────────────────────────────────────

    /**
     * Called by Fabric when this view instance is about to be reused.
     * Reset all state so the recycled view starts clean.
     */
    override fun prepareForRecycle() {
        dimOpacity   = 0.55
        cornerRadius = 12.0
        padding      = 6.0
        onTargetLayout = null
        UiThreadUtil.runOnUiThread {
            spotlightView.clear(durationMs = 0L)
        }
    }
}